### ISSUE TITLE
nanomsg 0.6

### ISSUE THREAD

**Issue by ksaritek** [nickdesaulniers/node-nanomsg#102]
forked nanommsg is at 0.5 version(feb 26). When sould nanomsg be upgraded?

**Comment by reqshark** [comment]
yea totally :loudspeaker: we're behind on that. it must get done. 

I thought I was going to have time to do it this weekend, eh... i guess I could do it next weekend

if you can't wait, send a PR

**Comment by reqshark** [comment]
updated and published to npm a9350236cf98da3cd24ca69c18c96f528e73692e
