### ISSUE TITLE
ecosystem upgrades

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#103]
## relevant ecosystem changes

- [ ] nan 2

#### beta 6 targets: 
- [x] windows
- [x] linx
- [x] osx

In addition to beta 6, let's use recently overhauled [native abstractions](https://github.com/nodejs/nan/issues/376) to compile against API breakage upstream in V8 4.4.63.26... like if we want to use iojs3. no more Handle, it's Local now. 

btw, @nickdesaulniers, iojs3 brings changes to node::buffer that I think we need to take a look at 

last week I was having some problems just getting nan2 off the ground but [that was NPM related](https://github.com/nodejs/nan/issues/405). I'll take another swing at it as soon as I can. In the meantime, PRs on any of these are most welcome :)

**Comment by thelinuxlich** [comment]
+1

**Comment by reqshark** [comment]
ok status update: got osx on beta6. building it on my machine running 10.11 El Capitan...

we're getting a few symbol test failures in `test/symbol.js` and `nn_device()` is killing the process. this is totally expected and @nickdesaulniers had to send a patch upstream earlier this year to libnanomsg in order to get our symbols test to pass, so upstream is again missing a couple symbols for export

here's the branch and i'll try to finish this up over the weekend for the other operating systems: https://github.com/nickdesaulniers/node-nanomsg/tree/beta6osx

*side note: the websocket stuff is compiling!* Take that snailzilla! :snail:

**Comment by reqshark** [comment]
linux is done.

```bash
$ git clone https://github.com/nickdesaulniers/node-nanomsg nano && cd nano
$ git checkout beta6
$ make
$ make check
```

**Comment by reqshark** [comment]
btw i'm going on vacation to Maui :palm_tree: starting tomorrow so if someone wants to do a PR for upgrading to nan 2, that would be awesome.  otherwise I'll get to it when i get back around mid sept

cc @kkoopa
