### ISSUE TITLE
ReqRep throws an error after a while

### ISSUE THREAD

**Issue by TEugen** [nickdesaulniers/node-nanomsg#105]
I have this running code, `server.js`:

```
var nano = require('nanomsg')
var tcp = 'tcp://127.0.0.1:9080'
var server = nano.socket('rep')

server.setEncoding('utf8')
server.bind(tcp)

server.on('data', function (data) {
  console.log('requested', data)
  server.send(data)
})
```

And two instances of this code, `client.js`:

```
var nano = require('nanomsg')
var ip = 'tcp://127.0.0.1:9080'
var client = nano.socket('req')

client.setEncoding('utf8')
client.connect(ip)

client.on('data', function (data) {
  console.log('data:', data, ' on 3', Date.now())
})

setInterval(function () {
  client.send('3')
}, 1000)
```

After a while I get this error:

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Operation cannot be performed in this state
    at Socket._protect (/Users/eugen/code/projects/vblaz/node_modules/nanomsg/lib/index.js:143:28)
    at Socket._send (/Users/eugen/code/projects/vblaz/node_modules/nanomsg/lib/index.js:172:17)
    at Socket.flush (/Users/eugen/code/projects/vblaz/node_modules/nanomsg/lib/index.js:268:14)
    at Socket.<anonymous> (/Users/eugen/code/projects/vblaz/node_modules/nanomsg/lib/index.js:199:30)
```

Seems to be a race condition somehow, I noticed the error is from `nanomsg`'s [source code](https://github.com/nanomsg/nanomsg/blob/master/src/utils/err.c#L103), but I don't know if is node related or what to report on `nanomsg`'s issue list.

**Comment by reqshark** [comment]
> After a while I get this error

you might already be doing this, but I guess until we figure out what that is, to keep your stream open and to prevent sockets from crashing the process, make sure to be err handling the stream:
```js
// .. client.connect(ip)

client.on('error', eek)

function eek (err) {
  console.log(err)
}

// client.on('data', function (data) { ...
```

also what's *after a while*, like ballpark how long is that duration?

**Comment by TEugen** [comment]
If you change the `setInterval` to 50ms and run 2 instances of `client.js` it usually happens in 3-4 seconds.

I use error handling, thanks for the suggestion tho', in this case once an error happens it keeps on throwing with every received message.

```
...
error [Error: Operation cannot be performed in this state]
error [Error: Operation cannot be performed in this state]
error [Error: Operation cannot be performed in this state]
error [Error: Operation cannot be performed in this state]
...
```

**Comment by reqshark** [comment]
ok so that's not a good use of the stream error handler, since the socket is left in an unrecoverable state.  basically you would have to reinitialize the socket during the error callback to keep things stable. 

thanks for the details, I'll try to reproduce it.  btw, are you using a unix or windows?

**Comment by TEugen** [comment]
I'm on OS X 10.10.4, haven't tried it on Linux yet'

**Comment by deepakprabhakara** [comment]
I ran into the same issue and have a potential fix - https://github.com/deepakprabhakara/node-nanomsg/commit/b90fb78c1033b204d3283f6ca1e9a0c7df361c1a

When the send-recv, send-recv state is broken in the reqrep protocol the rep socket ends up in a weird state. This fix calls _stopPollReceive in _receive and _startPollReceive in _send.

@reqshark I can send a pull request if you think this fix looks ok.

**Comment by reqshark** [comment]
@deepakprabhakara, LGTM, please send the PR

**Comment by nickdesaulniers** [comment]
we should add a unit test, that way we can prove the patch works

**Comment by nickdesaulniers** [comment]
@deepakprabhakara , if you want, you can add this test case to your PR:

test/bug105.js
```js
var nano = require('..')
var test = require('tape');

// see: https://github.com/nickdesaulniers/node-nanomsg/issues/105
test('multiple req sockets should not throw', function (t) {
  t.plan(1);

  var tcp = 'tcp://127.0.0.1:9080';
  var server = nano.socket('rep');

  var counter = 10;

  server.setEncoding('utf8');
  server.bind(tcp);

  server.on('data', function (data) {
    server.send(data);
    if (!(--counter)) {
      clearInterval(int1);
      clearInterval(int2);
      client.close();
      clientb.close();
      server.close();
      t.pass('no crashes');
    }
  })

  var client = nano.socket('req');

  client.setEncoding('utf8');
  client.connect(tcp);

  var int1 = setInterval(function () {
    client.send('3');
  });

  var clientb = nano.socket('req');
  clientb.setEncoding('utf8');
  clientb.connect(tcp);

  var int2 = setInterval(function () {
    clientb.send('3');
  });
});


```

I'll give you a week to send the PR, otherwise I'll just author the patch.

**Comment by reqshark** [comment]
@nickdesaulniers not author, you mean commit i think? let's just [`--amend` a commit](http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit) to deepak if the PR doesn't come soon

@deepakprabhakara is the author of the patch. I remember dealing with this problem, and not coming up with anything reasonable or elegant when back when i was writing req/rep and surveyor/respondent sockets on the nanomsg.iojs joint. so for fixing the long outstanding req/rep issue prabhakara should be added as a contributor too after this

**Comment by nickdesaulniers** [comment]
Is it ok to just take a patch like that without the authors consent?  I would not be comfortable without an explicit confirmation from @deepakprabhakara

**Comment by reqshark** [comment]
hmmm... makes sense, but i figured the implicit confirmation was:

> I can send a pull request if you think this fix looks ok.

**Comment by nickdesaulniers** [comment]
@reqshark , can you bump the patch level and publish?

**Comment by reqshark** [comment]
done

**Comment by deepakprabhakara** [comment]
Terribly sorry for the delay in responding to this. Thanks for adding the patch!
