### ISSUE TITLE
streams test timeout

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#110]
on the travis iojs test yesterday and once today already on the node v4.0.0 test I was getting a timeout on our: `pipe a thousand msgs between incompatible socket types`

https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/streams.js#L4 

i had to manually restart that otherwise it was just hanging so.. 

let's keep an eye on that travis CI timeout happening again and consider lowering the number of msgs to 300 or 500 or something, that would be a little easier for the travis box to handle during high load from everyone on github running their tests over there

**Comment by nickdesaulniers** [comment]
https://travis-ci.org/nickdesaulniers/node-nanomsg/jobs/79727401

**Comment by nickdesaulniers** [comment]
https://travis-ci.org/nickdesaulniers/node-nanomsg/jobs/79727503

**Comment by reqshark** [comment]
yea, i'm on it here #114

**Comment by reqshark** [comment]
we might have a better time of things by avoiding the guesswork of `setTimeout`, i.e. throughout the tests

check out #117, i'm adding an optional callback to `connect()` there

if that approach looks cool then I think we could use it for `nn_bind()`, `nn_close()` etc...

**Comment by reqshark** [comment]
hmm @nickdesaulniers, our timeout mystery could be related to #505, though admittedly that's more particular to WS timeouts than those we started seeing in September

**Comment by reqshark** [comment]
> In mangos I had some of these problems, so I used a repeated try protocol to determine when the connection was established (with an eventual timeout) before actually starting the real test.

-@gdamore

**Comment by nickdesaulniers** [comment]
so updating to 0.8 fixed this?

**Comment by reqshark** [comment]
well I think it could come back but after the update i couldn't get it to timeout
