### ISSUE TITLE
nn_close needs to check errno for EINTR

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#115]
from the man page: http://nanomsg.org/v0.6/nn_close.3.html

we're not checking the return code then errno: https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc#L35

**Comment by nickdesaulniers** [comment]
might be related to #110

**Comment by reqshark** [comment]
right you are

**Comment by nickdesaulniers** [comment]
I mean, you're the one that pointed it out, over IRC :frog: :dromedary_camel:
