### ISSUE TITLE
Release tags on master branch?

### ISSUE THREAD

**Issue by sirudog** [nickdesaulniers/node-nanomsg#127]
Hi, 

Did you consider using release tags on master branch (and a changelog.md maybe)? 
In my Jenkins CI setup I would like to get the 2.1.2 release by referencing a tag, instead of cloning directly the master branch (which is at the moment the latest version, but it is also the main branch for active development), so I can be always sure that even if there are newer releases/code introduced in master, I'll always stick to same version/codebase, and only switch to newer release once I have tested my projects with them.

**Comment by nickdesaulniers** [comment]
We definitely have plans for a changelog.  We can do tags, too!  Just curious, are you using node-nanomsg in a commercial project; if so, neat!

**Comment by reqshark** [comment]
+1 no question about it

**Comment by sirudog** [comment]
Great, thanks! 
@nickdesaulniers Not in a commercial project (yet), but working hard on it ... We want nanomsg to be the basis of our microservices solution for our (first internal, then hopefully commercial) platform.

**Comment by reqshark** [comment]
@sirudog I just started doing this. there should be a tag on master with a release now

**Comment by sirudog** [comment]
@reqshark Wow, that was fast! Thanks a lot! I am changing my CI setup right away...
