### ISSUE TITLE
update libnanomsg submodule

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#128]
we need to checkout a more recent copy of the lib, especially as the ongoing work to better meet RFC standards is taking place upstream

see https://github.com/nanomsg/nanomsg/issues/489

**Comment by nickdesaulniers** [comment]
Let's wait to grab the WS changes from 489 when fixed

**Comment by nickdesaulniers** [comment]
but #107 would be fixed now
