### ISSUE TITLE
expose new option: socket.rcvmaxsize()

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#138]
for background on the new socket option `NN_RCVMAXSIZE`, here's the original planning discussion: http://www.freelists.org/post/nanomsg/issue-with-received-message-size,1

[and from the `nn_setsockopt()` documentation](http://nanomsg.org/v0.8/nn_setsockopt.3.html):
> *NN_RCVMAXSIZE*
 Maximum message size that can be received, in bytes. Negative value means that the received size is limited only by available addressable memory. The type of this option is int. Default is 1024kB.

let's add a prototype method `rcvmaxsize()` like the rest of sockopt API. 

anyone sending msgs larger than the default will find this useful, to avoid unexpected close/disconnect

**Comment by nickdesaulniers** [comment]
> anyone sending msgs larger than the default will find this useful, to avoid unexpected close/disconnect

A sender can't know the receiver's `NN_RCVMAXSIZE` if changed from default, right?

**Comment by reqshark** [comment]
yea that's right. and moreover, from what I remember looking at the code change in libnanomsg for `NN_RCVMAXSIZE`, if msg sz is too big the connection gets closed... 

I'm not sure what to expect after that, we probably need to experiment or maybe add a test to find out, but it seems like a lot of attempts to reconnect is possible under this scenario

**Comment by reqshark** [comment]
hey if anyone want's to send a PR for this socket option, i'd love to review! :eyeglasses: 

otherwise I'll plan to get around to it probably next weekend
