### ISSUE TITLE
How to use AF_SO_RAW / AF_SP_RAW to create Zeromq ROUTER / DEALER equivalent?

### ISSUE THREAD

**Issue by yoshuawuyts** [nickdesaulniers/node-nanomsg#143]
I'm trying to create the following network setup:
```txt
 ┌──────────┐   ┌──────────┐   ┌──────────┐
 │  Client  │   │  Client  │   │  Client  │
 ├──────────┤   ├──────────┤   ├──────────┤
 │   REQ    │   │   REQ    │   │   REQ    │
 └──────────┘   └──────────┘   └──────────┘
       │              │              │
       └──────────────┼──────────────┘
                ┌─────▼────┐
                │  ROUTER  │
                ├──────────┤
                │  Broker  │
                ├──────────┤
                │  DEALER  │
                └──────────┘
                      │
       ┌──────────────┼──────────────┐
       │              │              │
 ┌─────▼────┐   ┌─────▼────┐   ┌─────▼────┐
 │   REP    │   │   REP    │   │   REP    │
 ├──────────┤   ├──────────┤   ├──────────┤
 │Service A │   │Service B │   │Service C │
 └──────────┘   └──────────┘   └──────────┘
```

I was looking how to create zeromq's `ROUTER` / `DEALER` in `nanomsg` and stumbled upon a [mailinglist](http://www.freelists.org/post/nanomsg/a-stupid-load-balancing-question,1) answer on how to achieve this.

Nanomsg's creator gave the following response:
> Just use `REQ`s, `REP`s and a device in the middle. When creating sockets
> for the device, use `AF_SP_RAW` family (`AF_SP_RAW`+`REQ` is what's called
> `DEALER` in ZeroMQ parlance, and `AF_SO_RAW`+`REP` corresponds to `ROUTER`).

This was slightly confusing to me, as I'm not very familiar with the `_RAW` variants in `nanomsg`. So my question is: how can I create a `ROUTER` / `DEALER` setup in `node-nanomsg`? Thanks!

**Comment by yoshuawuyts** [comment]
Ah, so it appears load balancing is built into `REQ` and `PUSH` sockets, which clarifies the idea behind it a little; we no longer have to think about how to round robin (or in this case, have a multi-tier round robin) to balance the load. All that I'm curious about now is how to wire up the sockets so they're actually connected.

- http://250bpm.com/blog:14

**Comment by reqshark** [comment]
hey that's a good link, i'm also a fan of: http://250bpm.wdfiles.com/local--files/publications/ietf.pdf

> Ah, so it appears load balancing is built into REQ and PUSH sockets

that's right, REQ/REP was designed around the need to distribute precise load balancing tasks among stateless workers. There's also PUSH/PULL, discussed some in #118. 

@yoshuawuyts, i think RAW sockets usually need sudo permissions like the low ports, but I'm not 100% if that's the case on every operating system and for every AF_SP_RAW combo

**Comment by reqshark** [comment]
OK I think we only use RAW sockets at the local proxy endpoint, Martin says it's intended for `nn_device()` which is basically `zmq_proxy()` or `xpub/xsub`, etc. from zeromq 

here's the better answer: http://www.freelists.org/post/nanomsg/AF-SP-RAW-vs-AF-SP,1

**Comment by yoshuawuyts** [comment]
Ah right, so `nano.device` / `nano.createDevice` is exposed but not mentioned in the documentation. Mentioning stuff like [`nano.term()`](https://github.com/nickdesaulniers/node-nanomsg/blob/5d8e9da12b4b9d44580c0046b8d0bed19a603319/test/standalone/device.js#L45) might be good to have in there.

It appears there's some tests around `device` and `raw: true`:
- [unidirectional device](https://github.com/nickdesaulniers/node-nanomsg/blob/5d8e9da12b4b9d44580c0046b8d0bed19a603319/test/standalone/device2.js)
- [bidirectional device](https://github.com/nickdesaulniers/node-nanomsg/blob/5d8e9da12b4b9d44580c0046b8d0bed19a603319/test/standalone/device.js)

This should work with transports other than `inproc` too right?

**Comment by reqshark** [comment]
yes it would definitely be useful, @yoshuawuyts would you be up for a PR?
