### ISSUE TITLE
router-dealer implementation

### ISSUE THREAD

**Issue by renesamaral** [nickdesaulniers/node-nanomsg#147]
Hi, i'm searching a API to handle messages by two node apps, and i found zeromq and maked some tests with the req/rep pattern using async with multiples clients and multiples workers, using the pattern router-dealer of zeromq with async! can i implement the router-dealer in node-nanomsg with multiples clients making multiples requests via req/rep with load balance ? Thanks and sorry for my english!

**Comment by aliem** [comment]
This is what you are looking for: https://github.com/nickdesaulniers/node-nanomsg/blob/master/examples/pipeline.js

Push and pull sockets. The `push` socket will be your server sending data to the connected `pull` sockets using round robin.

**Comment by renesamaral** [comment]
Hi! Ty for the fast answer! But in pattern of PULL/PUSH is one directional, correct? I need a REQ/REP, where my client sent a message to a worker execute a process and the worker need to reply the message to my client with a message! With the pipeline example is it possible ?

**Comment by reqshark** [comment]
sounds like a good use case for nn_device, see #145
