### ISSUE TITLE
linux assertion failed: 8 == NN_USOCK_STATE_ACTIVE

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#152]
I had the following assert crash my program on linux:

```c
Assertion failed: 8 == NN_USOCK_STATE_ACTIVE (../deps/nanomsg/src/aio/usock_posix.inc:461)
```

and https://github.com/nanomsg/nanomsg/issues/645 appears to be fixed upstream https://github.com/nanomsg/nanomsg/issues/663

so we'll have to cut an update for that shortly

**Comment by reqshark** [comment]
heh, well just kidding, this isn't ready yet... :fallen_leaf:

**Comment by nickdesaulniers** [comment]
:fireworks:
