### ISSUE TITLE
windows: some problems when im compiling

### ISSUE THREAD

**Issue by 0x452** [nickdesaulniers/node-nanomsg#154]
hello everyone,

when im compiling node-nanomsg i get a lot of errors:
`cannot open include 'nn.h'`

i had installed simple nanomsg and other stuff but it still not working

**Comment by yoshuawuyts** [comment]
@swiftS2K what version of `node` and `npm` are you running? Could you perhaps post the full `npm-debug.log` output? Thanks!

**Comment by swiftS2K** [comment]
thanks for answering
[npm-debug.txt](https://github.com/nickdesaulniers/node-nanomsg/files/275867/npm-debug.txt)

**Comment by yoshuawuyts** [comment]
Looks like you're running on Windows - I'm not overly familiar with it, and don't have access to a machine running it, so I think I won't be any help here :|

Perhaps consider running Node inside a VM? Maybe one of the maintainers knows what's up? Good luck!

**Comment by reqshark** [comment]
thanks @yoshuawuyts, yea windows is currently unsupported. 

@swiftS2K, please help fix our windows build with a PR!

i plan to look into it this week, we should try to make it work on windows for the nanomsg beta-09 update

**Comment by 0x452** [comment]
@reqshark problem still exist :(
i can not build on windows

**Comment by reqshark** [comment]
i know sorry been really busy lately

**Comment by nickdesaulniers** [comment]
From the [logs posted](https://github.com/nickdesaulniers/node-nanomsg/issues/154#issuecomment-220776870), it looks like the reporter tried to install with:
`npm install nanomsg --use_system_libnanomsg=true`.

So whatever commit added support for that option wasn't tested on Windows.  I don't think this is a regression; I think it never worked in the first place.

**Comment by reqshark** [comment]
@nickdesaulniers that's right, but at a minimum we ought to be able to run the module on windows

**Comment by reqshark** [comment]
@0x452, can you try installing `nanomsg@3.2`?

3.2.0 updates libnanomsg to release version 1.0, also bringing back Windows support in node-nanomsg

**Comment by 0x452** [comment]
@reqshark yes, that works. thanks!

im so late :laughing:

**Comment by reqshark** [comment]
awesome, glad we got it fixed for windows!

**Comment by nickdesaulniers** [comment]
💥 🎉
