### ISSUE TITLE
beta-09 changes

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#155]
beta-09 is ready to go for unix on a release WIP branch candidate: https://github.com/nickdesaulniers/node-nanomsg/commits/0.9-beta

• nanomsg `term()` is a little different now (more POSIX-like according to @gdamore)
• IPC protocol and its leftovers have been revamped *
• new [`nn_get_statistic` API](http://nanomsg.org/v0.9/nn_get_statistic.3.html) gives us programatic access to socket activity

I'm going to hold off on publishing to npm for the next few days because I think we can restore access to the module from a windows to fix #154... and I'd love to roll that all up together our beta-09 update

\**Essentially, after IPC transport sockets close, there's a remainder unix domain socket/file at the address whose descriptor path is no longer automatically cleaned up by the library. As a result, it could easily prevent subsequent IPC protocol exchange from BIND/CONNECT at the same namespace address, unless we clear out and proactively remove the file*

**Comment by reqshark** [comment]
actually lets do a beta 09 now and plan on releasing 1.0 with full windows support

see last line of this email if you read nothing else: http://www.freelists.org/post/nanomsg/bind-is-synchronous-mostly

**Comment by 0x452** [comment]
Thanks alot ☺
