### ISSUE TITLE
An example for streams with back pressure

### ISSUE THREAD

**Issue by dremekie** [nickdesaulniers/node-nanomsg#172]
Take the following two files:

push.js
```javascript
var nano = require('nanomsg');
var push = nano.socket('push');
var fs = require('fs');
var byline = require('byline');

push.bind('ipc:///Users/dwayne/tmp.ipc');

const linestream = byline(fs.createReadStream('/Users/dwayne/Documents/projects/big-file.json', { flags: 'r', encoding: 'utf8' }));
linestream.pipe(push); 
```

pull.js
```javascript
var nano = require('nanomsg');
var pull = nano.socket('pull');

pull.connect('ipc:///Users/dwayne/tmp.ipc');
pull.pipe(process.stdout);
console.log('waiting...');
```

Two observations.

1. When both push.js and pull.js are started, only a cartain number of lines are written before the following occurs:

```bash
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Resource temporarily unavailable
    at Socket._protect (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:144:28)
    at Socket._send (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:173:17)
    at Socket.flush (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:273:14)
    at Socket.<anonymous> (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:204:30)
```

The same occurs when using basic filestream. fs.createReadStream('/Users/dwayne/Documents/projects/test/big-file.json').

Why would this happen?

2. When push.js is running and pull.js is not running, memory builds up as the lines of the file is "queued up" internally. Is that expected? Shouldn't back pressure prevent this from happening?

**Comment by reqshark** [comment]
interesting error. I'm curious:
* what operating system are you running?
* can you replace your current nanomsg module w/ the branch i just made?

```
rm -rf node_modules/nanomsg
git clone https://github.com/nickdesaulniers/node-nanomsg.git node_modules/nanomsg
cd node_modules/nanomsg && git checkout blockcalls && git submodule update --init
npm install
```

and then after that run your push/pull sockets in the same way. does that fix anything?

**Comment by reqshark** [comment]
@dremekie, got another question: 

what happens when you use tcp protocol instead of ipc?

**Comment by reqshark** [comment]
also.. just thought of a way easier alternative to cloning that branch: `npm i nanomsg@3.2.0`

**Comment by dremekie** [comment]
@reqshark will give it a go and report back shortly

**Comment by dremekie** [comment]
also... using Mac OSX

**Comment by dremekie** [comment]
@reqshark That solved problem #1 above. Thanks very much.

For #2, the issue is still there. So this now comes down how streams are implemented. There seems to be no back pressure. I read from a filestream (a very large file) and I pipe to the PUSH socket. In my case, it queued up pushed content until there was no more memory left and crashed the process.

Is there a way for the receiving PULL socket(s) (since there may be several) to ask the PUSH socket to supply more data only as required (typical back pressure stuff)?

**Comment by reqshark** [comment]
> There seems to be no back pressure.

yea at this point our PUSH/PULL sockets aren't too useful--it's just round-robin.

> So this now comes down how streams are implemented.

An intermediary between your source data stream and the PUSH socket, like a transform throttling mechanism might help.

And sure, we could set the library/kernel `setsockopt()` to block (or not) during `send()` operations, but doing so would be pointless if JavaScript land eventloop is not completely aligned, i.e. blocked while libnanomsg performs the blocking call.

> it queued up pushed content until there was no more memory left and crashed the process.

Try to always bind/connect PULL sockets first. You'll want to do this before bind/connect on PUSH.

> Is there a way for the receiving PULL socket(s) (since there may be several) to ask the PUSH socket to supply more data only as required (typical back pressure stuff)?

that sounds like a nice description of REQ/REP, patterned specifically for ACK from the other side

**Comment by dremekie** [comment]
Understood. Thanks for the information.

**Comment by reqshark** [comment]
@dremekie, np! 

and thanks for uncovering the bug in #173 :)
