### ISSUE TITLE
NN_DONTWAIT triggers JS stream/event error for PUSH ipc:// under msg load

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#173]
protocol might not matter, but some cause and effect observed in #172, reported by @dremekie: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Resource temporarily unavailable
    at Socket._protect (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:144:28)
    at Socket._send (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:173:17)
    at Socket.flush (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:273:14)
    at Socket.<anonymous> (/Users/dwayne/Documents/projects/test/node_modules/nanomsg/lib/index.js:204:30)
```

Resource temporarily unavailable is associated with `EAGAIN` or `EWOULDBLOCK` -[`errno` man page](http://man7.org/linux/man-pages/man3/errno.3.html)

`NN_DONTWAIT` puts the socket into non-blocking I/O mode, which may lead to either an `EAGAIN` or `EWOULDBLOCK` when the send buffer is completely full. 

from my `send` manual page:
```bash
If no messages space is available at the socket to hold the message to be transmitted,
then send() normally blocks, unless the socket has been placed in non-blocking I/O mode
```

A PUSH socket's send buffer could max out when calls to `send()` accumulate without a drain from PULL socket's `recv()`. In cases like these, if the OS suggests `EAGAIN`, error: try again... an ideal retry would wait some time to allow PULL socket activity against the filled send buffer.

In Node.JS, users should listen for this error on a PUSH stream like `push.on('error', function(e)` and make sure to set a reasonable timeout before retrying that pipe.

In the meantime, 

@nickdesaulniers, we can:
* expose `NN_DONTWAIT` flag to the user as another generic piece of the `sockopt()` api, or
* don't set the send flag for PUSH (or problem could also be send flag on`ipc://`)

Not setting the flag seems to fix `Resource temporarily unavailable` in #172

**Comment by nickdesaulniers** [comment]
> expose NN_DONTWAIT flag to the user as another generic piece of the sockopt() api, or

Seems easy and straightforward.  With documentation, it shouldn't be too bad for users to figure out when they need this.

> don't set the send flag for PUSH (or problem could also be send flag onipc://)

lower mental burden for users, but not sure that those are the only cases that we need them.

In general, I think I prefer to expose more low level (where we maintain C++ to JS translation layer).  If someone wants to build a higher level abstraction on top of us, we provide the tools for them to do so.  Ultimately, you understand the problem more than I do, and I trust you, so I will defer to you. 🗝

**Comment by reqshark** [comment]
thanks @nickdesaulniers! 

> not sure that those are the only cases that we need them

yea, great point

so i think we can kill two birds with one stone here by setting defaults that make sense, like in the case of PUSH or `ipc://` and expose the option to override our defaults

I'll work on something like that and try to get a PR out later this week :)
