### ISSUE TITLE
add support for NN_MAXTTL socket option

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#180]
forked from #179 
```
NN_TTL
Retrieves the maximum number of "hops" a message can go through before it is dropped. Each time the message is received (for example via the nn_device(3) function) counts as a single hop. This provides a form of protection against inadvertent loops.
```

http://nanomsg.org/v1.0.0/nn_getsockopt.3.html

**Comment by nickdesaulniers** [comment]
looks like we got NN_MAXTTL in nanomsg 1.1.0 upgrade: https://github.com/nickdesaulniers/node-nanomsg/commit/db4ce9c464b4cf8aeb76b897c7e67559da549ef3#diff-24ffb94f7602175de6d25f07245886a8R441 @reqshark

**Comment by reqshark** [comment]
then let's add it to the sockopt api
