### ISSUE TITLE
nanomsg 1.1.0 is out

### ISSUE THREAD

**Issue by deepakprabhakara** [nickdesaulniers/node-nanomsg#181]
Can I please request a new release since nanomsg v1.1.0 has just been released.

Regards.
Deepak.

**Comment by reqshark** [comment]
Hi Deepak, thanks for pointing this out, 

definitely need to update, esp. if we hope to expose `NN_TTL` socket option #180

**Comment by nickdesaulniers** [comment]
https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/mksymbols.rb is broken with the latest release.  Need to be able to run it otherwise tests start failing.

**Comment by nickdesaulniers** [comment]
a bunch of tests are now triggering warnings:

```
(node:4821) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

```
➜  node-nanomsg git:(master) ✗ node -v
v8.4.0
```
maybe specific to my version of node?

**Comment by nickdesaulniers** [comment]
deprecation warnings are fixed by using fs.unlinkSync rather than fs.unlink.

**Comment by nickdesaulniers** [comment]
https://github.com/nanomsg/nanomsg/commit/327a29b1a614131697c4be5da599dcc8368fdf04#diff-3869029c9e50f872a70345a5e53bb9f4 modified the struct so we need to update mksymbols.rb. Working on that now.

**Comment by deepakprabhakara** [comment]
v1.1.2 is out and has a few fixes, so might be worth upgrading to that version.

**Comment by nickdesaulniers** [comment]
I tested on Linux, so not sure it's necessary.  Maybe some users with an odd/old build of glibc might be affected.

**Comment by deepakprabhakara** [comment]
@nickdesaulniers Aah v1.1.1 has some fixes that seem relevant - https://github.com/nanomsg/nanomsg/releases/tag/1.1.1 , v1.1.2 just seems to be a complication fix.

**Comment by reqshark** [comment]
might be nice to first do a release for v1.1.0 and bump major (node-nanomsg 4.0.0)

(still have a couple minor PRs outstanding that need Nick's review) 

and then we could push out two more PATCH updates for v1.1.1 and v1.1.2.

What do you guys think?

**Comment by reqshark** [comment]
also we might not actually be using that code in v1.1.1 since i don't think we're using any of the nanomsg built in polling mechanisms, we're doing our own polling from libuv
