### ISSUE TITLE
socket.close() does not remove socket file for IPC

### ISSUE THREAD

**Issue by art32** [nickdesaulniers/node-nanomsg#191]
Example:
```JS
const nn = require('nanomsg');
const push = nn.socket('push');

push.bind('ipc:///tmp/server.ipc');

process.on('SIGINT', () => {
    console.log(push.close());
    process.exit();
});
```

Run ```node test.js``` and press ```Ctrl + c```.
push.close() return ```0``` but ```/tmp/server.ipc``` is not deleted and re-run I cant't.

node: 8.9.3
node-nanomsg: 4.0.0
OS X 10.13.1

**Comment by nickdesaulniers** [comment]
What happens if you `bind` then immediately `close` without waiting for sigint?

**Comment by art32** [comment]
Same.

```JS
const nn = require('nanomsg');
const push = nn.socket('push');

push.bind('ipc:///tmp/server.ipc');
console.log(push.close())
```
First run returned ```0```
Second run throw error ```Error: Address already in use```

I check this case on Centos 7 and it is the same behavior.
