### ISSUE TITLE
nanomsg on windows

### ISSUE THREAD

**Issue by DrYSG** [nickdesaulniers/node-nanomsg#197]
I know you say it is not been tested on windows. But here is what I get when I try to installl:

(Where does it say one needs python?)

```
D:\Source\Orchestrator\orchestrator>npm install nanomsg

> nanomsg@4.0.2 install D:\Source\Orchestrator\orchestrator\node_modules\nanomsg
> node-gyp rebuild


D:\Source\Orchestrator\orchestrator\node_modules\nanomsg>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Source\Orchestrator\orchestrator\node_modules\nanomsg
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nanomsg@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nanomsg@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by DrYSG** [comment]
Basically, before hacking, I would not mind knowing if anyone got this to work

**Comment by reqshark** [comment]
ya it works, install python. I recommend the anaconda version. https://www.anaconda.com/download/

**Comment by DrYSG** [comment]
@reqshark 

Thanks Ben. I did the install, and added the PYTHON env variable, but I am still getting this message:

gyp ERR! stack Error: Can't find Python executable "D:\Program Files (x86)\Python37-32\python.exe", you can set the PYTHON env variable.

It is a system env variable. I also tried just having the directory for the PYTHON, but even though the exe is there, it is not finding it for some reason.

**Comment by reqshark** [comment]
are you able to install other native bindings?

**Comment by DrYSG** [comment]
I try not to use node stuff that depends on native bindings. In this case, I can see why it might be needed.

I think my issue is more about how to setup node-gyp for the python path.

https://stackoverflow.com/questions/52042568/node-gyp-cannot-find-python-executable

**Comment by reqshark** [comment]
yea the issue is unrelated to node-nanomsg

**Comment by DrYSG** [comment]
@reqshark The issue was that node-gyp only understands Python2.x Perhaps you should add to python to the readme, andtell them that they cannot just have python.exe on the path, but need to add this to the .npmrc

python=D:\Program Files (x86)\Python27\python.exe

or whatever the path is.

**Comment by reqshark** [comment]
@DrYSG, would you care to make a PR with your note in the readme, like a

### tip for installing on windows:
you may need to set your particular python path in `.npmrc`:
`python=D:\Program Files (x86)\Python27\python.exe`

**Comment by DrYSG** [comment]
@reqshark I would love to, but our issue is that we do a lot of DOD business, so our firewall keeps me for doing simple things like PRs.

**Comment by nickdesaulniers** [comment]
I think you can edit readme's entirely from github's web interface.

**Comment by DrYSG** [comment]
Fork and edit yes, but I don't see an in-place edit.

 BTW @nickdesaulniers , I combined this with Google Flatbuffers and am using the bus protocol. I wrote a trigger/action engine, and in all of less than 4 hours and 50 lines of code, the whole things works. Fantastic. Thank you so much.
