### ISSUE TITLE
add support for nng

### ISSUE THREAD

**Issue by nullr0ute** [nickdesaulniers/node-nanomsg#202]
nng is the new upstream replacement to nanomsg https://github.com/nanomsg/nng

It would be useful to be able to use either the older nanomsg while providing a migration path to nng

**Comment by snailuj** [comment]
I don't know enough about the build process to comment, but `nng` has API compatibility with `nanomsg` as one of its core aims, so once the `cmake` change is made there **may** only be a few changes required to the `node-nanomsg` C++ files.

> Today `nng` offers this. You can relink an existing `nanomsg` binary against `libnng` instead of `libnn`, and it usually Just Works™. Source compatibility is almost as easy, although the application code needs to be modified to use different header files. I am considering changing the include file in the future so that it matches exactly the nanomsg include path, so that only a compiler flag change would be needed.
https://nanomsg.github.io/nng/RATIONALE.html

**Comment by nickdesaulniers** [comment]
I think nng should be a different library than node-nanomsg. It's non
trivial to write nodejs native libraries (C++), and you can't just swap
them out. Nng may be api compatible, but I'll bet it's not abi compatible,
so it's not like it's a drop in replacement for us.

**Comment by nickdesaulniers** [comment]
> and i wonder if there's a nice way to do an npm install with a cmake process

If possible, I wonder if we could just provide `.so`, `.dll`, and `.dylib` prebuilt files.  gyp needs to go in the trash bin.

**Comment by reqshark** [comment]
> I think nng should be a different library than node-nanomsg.

after looking into NNG a bit more I agree with Nick, we can close this issue/question

### problem 1

> Nng may be api compatible, but I'll bet it's not abi compatible, so it's not like it's a drop in replacement for us.

a lot of new api plus clearly something there to preserve our current libnanomsg operations:

```c
// This file supplies the legacy compatibility API.  Applications should
// avoid using these if at all possible, and instead use the new style APIs.
```

https://github.com/nanomsg/nng/blob/master/src/compat/nanomsg/nn.c

Not the real issue! Interface compatibility is like the last hurdle to an nng integration w/ nodejs

### problem 2
this is our real issue and the basis for separating a node-nng module into a different binding 

we have the nontrivial prerequisite to build and compile nng as C/C++11 binaries for direct execution from the node.js runtimes. nng uses a totally different build process than the versions of libnanomsg we're building for nodejs
