### ISSUE TITLE
are we handling scopes correctly?

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#216]
maybe a question for @kkoopa , but reading https://github.com/nodejs/nan#scopes, and seeing the occasional use of `Nan::HandleScope` in https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc, it made me think that many of our calls to `Nan::new` are not scoped correctly.  I wonder if this leads to leaked memory?

**Comment by kkoopa** [comment]
Everything looks laright at a glance.

> You do not need to declare a new HandleScope within a method as one is implicitly created for you.

https://github.com/nodejs/nan/blob/master/doc/methods.md#api_nan_method
