### ISSUE TITLE
Electron compatibility: "Loading non-context-aware native module in renderer"

### ISSUE THREAD

**Issue by dljsjr** [nickdesaulniers/node-nanomsg#222]
By default, Electron does not allow you to use Node.js features in renderer processes. But if this is enabled and you attempt to load node-nanomsg you will get the following as an error unless you set `app.allowRendererProcessReuse` to `false`, at which point you still get this as a warning.

https://github.com/electron/electron/issues/18397

**Comment by reqshark** [comment]
before that flag there was another way to do it, see #196.

electron's generic warning for node bindings seems pretty unrelated to node-nanomsg so gonna mark this issue closed

feel free to reopen for discussion if there's something we can do on our side to make electron happier about the native module context
