### ISSUE TITLE
(node:660) electron: The default of contextIsolation is deprecated and will be c hanging from false to true in a future release of Electron.  

### ISSUE THREAD

**Issue by dnybz** [nickdesaulniers/node-nanomsg#224]
Hi, i am use electron 11.0.3  (Node.js 12.18.3, Chromium 87.0.4280.67, and Electron 11.0.3)

run app errors:

(node:660) electron: The default of contextIsolation is deprecated and will be c
hanging from false to true in a future release of Electron.  See https://github.
com/electron/electron/issues/23506 for more information
(node:13928) Electron: Loading non-context-aware native module in renderer: '\\?
\G:\workspace\project\trunk\src\electron-client\appclient\node_modules\nanomsg\bui
ld\Release\node_nanomsg.node'. This is deprecated, see https://github.com/electr
on/electron/issues/18397.

https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc#L286

//NODE_MODULE(node_nanomsg, InitAll)
#if NODE_MAJOR_VERSION >= 10
NAN_MODULE_WORKER_ENABLED(node_nanomsg, InitAll)
#else
NODE_MODULE(node_nanomsg, InitAll)
#endif

rebuild ok ~

**Comment by Bartel-C8** [comment]
So @dnybz , how did you solve this?

**Comment by Bartel-C8** [comment]
Actually, your solution solved it. I was just rebuilding it wrongly (with yarn rebuild / npm rebuild). But I was using electron-rebuild, which was/should be responsible of rebuilding the native module correctly (with the correct (ABI) version of Electron).

Thanks!
