### ISSUE TITLE
merge nanomsg.iojs

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#45]
Looking to adopt some of the API changes from nanomsg.iojs and possibly custom event model.  cc @reqshark see also https://github.com/reqshark/nanomsg.iojs/issues/19

@reqshark you now have commit bits.  For anything that changes existing APIs, let's use PRs and code reviews, but otherwise feel free to commit to master for smaller changes.

**Comment by reqshark** [comment]
:+1: awesome, PRs in the works!

**Comment by nickdesaulniers** [comment]
https://github.com/reqshark/nanomsg.iojs/commit/e3b4ca7709e9e4120459bddff0ed416a0d4b3e9e

**Comment by reqshark** [comment]
we're almost done with this

**Comment by nickdesaulniers** [comment]
fixed in #53
