### ISSUE TITLE
buffer error: kMaxLength 

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#47]
running the test suite on osx and linux i get a buffer triggered assertion crap out on [`survey.js`](https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/survey.js).

also wondering why tape is zero for zero when `t.plan(4)` :

```c
ok survey.js ........................ 0/0
TAP version 13
Assertion failed: (length <= kMaxLength), function New, 
file ../src/node_buffer.cc, line 145.
```

**Comment by nickdesaulniers** [comment]
From current master c476019 or with #46 applied?

**Comment by reqshark** [comment]
its on current master, and it's not a timeout, but scroll up to the results on to see survey.js after you get:

```js
total ........................... 806/806

ok
```

**Comment by nickdesaulniers** [comment]
```
ok survey.js ........................ 4/4
TAP version 13
```

**Comment by reqshark** [comment]
dont see the assertion error on node 10.. using osx yosemite. still `0/0`, but silent as to why 

linux assertion error is different, points at `node::Environment*`, whereas i'm not seeing that on yosemite.

linux:
```js
ok survey.js ........................ 0/0
TAP version 13
node: ../src/node_buffer.cc:121: v8::Local<v8::Object> node::Buffer::New(node::Environment*, size_t): Assertion `(length) <= (kMaxLength)' failed.
```

is `darwin 10.8.5` is that much different?

**Comment by nickdesaulniers** [comment]
If I upgrade to node v0.12.0 from v0.10.26 I see this.

```
ok survey.js ........................ 0/0
TAP version 13
Assertion failed: (length <= kMaxLength), function New, file ../src/node_buffer.cc, line 145.
```

**Comment by nickdesaulniers** [comment]
I wonder where `node_buffer.cc` is?

**Comment by nickdesaulniers** [comment]
Also, I bet we shouldn't be using uint32's somewhere:
https://github.com/joyent/node/issues/4331

**Comment by nickdesaulniers** [comment]
node_buffer.cc: https://github.com/joyent/node/blob/master/src/node_buffer.cc#L145

**Comment by nickdesaulniers** [comment]
@trevnorris, any idea how I should go about debugging this?  Should I try to get a stack trace from an assertion?

I should be able to run that one test individually with `./node_modules/.bin/tapr test/survey.js`.

**Comment by nickdesaulniers** [comment]
It's definitely this line that is triggering it: https://github.com/nickdesaulniers/node-nanomsg/blob/1620d3b60df1f9635169308405f2d1e4cf13464f/lib/index.js#L134

**Comment by nickdesaulniers** [comment]
it fails because `len` is -1: https://github.com/nickdesaulniers/node-nanomsg/blob/0ffb39f1a4fd4cab521a6d0cbd746b4073a57c3e/src/node_nanomsg.cc#L198

**Comment by nickdesaulniers** [comment]
ah, this patch removed a necessary check https://github.com/nickdesaulniers/node-nanomsg/commit/c0336f19cd637660731f32911d1f31b09e6f7f8f

**Comment by reqshark** [comment]
fixed https://github.com/nickdesaulniers/node-nanomsg/commit/c50541c58fe9260aacfe65699a020615e549f807

**Comment by reqshark** [comment]
@nickdesaulniers good catch!
