### ISSUE TITLE
clean up deprecation warnings

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#49]
```
➜  nanomsg git:(master) ✗ rm -rf node_modules
➜  nanomsg git:(master) ✗ npm install
npm WARN deprecated tap-consumer@0.0.1: this is merged into the 'tap' module now
npm WARN deprecated tap-results@0.0.2: this is merged into the 'tap' module now
```

**Comment by nickdesaulniers** [comment]
These are in tap, but updating tap to 0.6.0 doesn't remove the deprecation warnings???

**Comment by rmg** [comment]
These deprecations are indeed from an old version of tap, but it's not the version you are depending on. It's the version that tapr is pulling in, which hasn't been updated in 3 years and still lists an ancient version of tap as a dependency.

From your package.json it looks like you aren't actually using the tap module at all. You are using using tapr as a test runner but using tape as your test harness, and not at all using mocha, chai, or tap, which are all listed in your devDependencies.

**Comment by nickdesaulniers** [comment]
Ah nice find.  @rmg , are there any automated way of listed unnecessary dependencies listing in a package.json?  As a project grows, it's hard to keep track of what is no longer necessary.  CSS rules remind me of this.

**Comment by rmg** [comment]
I find https://www.npmjs.com/package/dependency-check to work well for both missing and unused dependencies.
