### ISSUE TITLE
NN_RCVPRIO symbol not exported

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#50]
this is an issue with the `nn` binding in our javascript.

for the new `rcvprio` option function, we're having to go: 

```js
/**
 * generic socket-level NN_SOL_SOCKET options
 */
var sol = {
  linger          : nn.NN_LINGER,
  sndbuf          : nn.NN_SNDBUF,
  rcvbuf          : nn.NN_RCVBUF,
  sndtimeo        : nn.NN_SNDTIMEO,
  rcvtimeo        : nn.NN_RCVTIMEO,
  reconn          : nn.NN_RECONNECT_IVL,
  maxreconn       : nn.NN_RECONNECT_IVL_MAX,
  sndprio         : nn.NN_SNDPRIO,
  rcvprio         : 9,
  tcpnodelay      : nn.NN_TCP_NODELAY,
}
```

**Comment by nickdesaulniers** [comment]
running ` cd test && ./mksymbols.rb > symbols.js` removes NN_RCVPRIO from `test/symbols.js`.  We [parse this value](https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/mksymbols.rb#L10-L17), from [here](https://github.com/nanomsg/nanomsg/blob/a1a17e12a78cca4c0b37175e0200dc2fbcc3b6be/src/core/symbol.c#L145-L146) which itself is missing definitions for NN_RCVPRIO!

**Comment by nickdesaulniers** [comment]
And it's still missing in master.  This must be a bug upstream in nanomsg!

**Comment by nickdesaulniers** [comment]
https://github.com/nanomsg/nanomsg/pull/375
