### ISSUE TITLE
measuring performance

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#60]
@comick, thanks again for that contribution fb0b0571c6e54a21cab1b0c722e1184b1f0c5aa1 to our perf scripts today! looks great! :+1:  

I think it would be nice if we could measure/compare performance of node.js strings as well as buffers. 

either allowing for an additional option or maybe just adding some different scripts altogether

comparing the latency and throughput of messages against these two types of input we regularly handle in our node programs would determine the right way to structure input to our topologies. 

But also in particular: inform us whether and to what extent https://github.com/nickdesaulniers/node-nanomsg/pull/56 impacts the module, and other perf oriented additions we add in the future.  

thoughts?

**Comment by comick** [comment]
Makes sense to keep default pers scripts exactly the same as the nanomsg one.
Nevertheless we can ann options which are strictly related to the node module bounties.
Something like --string --buffer would make the job.

**Comment by reqshark** [comment]
yes! great idea!

**Comment by reqshark** [comment]
fixed by d1ab5a6a96abe3776c4cf80a309c0862402f7c29
