### ISSUE TITLE
drop support for NN_SOCKET_NAME

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#67]
[Our code](https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc#L106-L119) for handling getting the socket name is ridiculous.  I'm going to rip out support for this functionality, since its basis is marked as experimental:

https://github.com/nanomsg/nanomsg/blob/a6dcc0ce7cf489e957e6f07ca756ac66f2420b36/doc/nn_getsockopt.txt#L107-L110
http://nanomsg.org/v0.5/nn_env.7.html

@blowback , the code has [your name](https://github.com/nickdesaulniers/node-nanomsg/blame/master/src/node_nanomsg.cc#L106-L119) on it.  Will you be affected?

**Comment by nickdesaulniers** [comment]
Also: https://github.com/nickdesaulniers/node-nanomsg/blob/master/src/node_nanomsg.cc#L151-L158 and everywhere else NN_SOCKET_NAME is.

**Comment by reqshark** [comment]
I'm rewriting some of this right now in #65

**Comment by blowback** [comment]
Go for it!

**Comment by reqshark** [comment]
@blowback ok cool thanks!

**Comment by nickdesaulniers** [comment]
Fixed in PR: #65
