### ISSUE TITLE
update socket.shutdown

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#70]
@nickdesaulniers, we should probably implement this method [the way we say it's implemented](https://github.com/nickdesaulniers/node-nanomsg#socketshutdownaddress).

### socket.shutdown(*address*)

call `shutdown(str)` w/ an address string to detach the socket connected/bound to that address.

makes way more sense than [trying to cope with obscure return values](https://github.com/nickdesaulniers/node-nanomsg/blob/0a44b5ec46811a3941d8c563666270303c3c5ed9/lib/index.js#L280): libnanomsg's `how` integer returned by low level calls to [`nn_bind()`](http://nanomsg.org/v0.5/nn_bind.3.html) or [`nn_connect()`](http://nanomsg.org/v0.5/nn_connect.3.html).

I think we just need to tuck that weird implementation detail into a new object property on the JS socket and use the `delete` operator to clear it when `shutdown()` gets called. No biggie... 

I'll PR that one after lunch tomorrow and we won't have to worry about updating the docs :)

**Comment by nickdesaulniers** [comment]
fixed in #71
