### ISSUE TITLE
How to catch nanomsg timeout ?

### ISSUE THREAD

**Issue by GrimDev** [nickdesaulniers/node-nanomsg#73]
Hi !

Since many days, i try to catch nanomsg timeout.

I set rcvtimeo and sndtimeo at 100, and tyed to catch it with socket.on("error") and socket.on("timeout") but that never occurs.

Can I have some help please.

Thx.

**Comment by reqshark** [comment]
hi @GrimDev, sndtimeo and rcvtimeo aren't going to emit either of those events. 

All they are designed to do is delay send or recv operations on the socket. 

Can you paste your code so we can take a look?

**Comment by GrimDev** [comment]
Thanx for your quick reply.

See my code bellow (coffee script)

# I create my socket in pair
console.log "init"
@socket = nano.socket("pair")
addr = "tcp://0.0.0.0:1665"
sock = @socket.bind addr

# Set snttimeo and rcvtimeo at 100
@socket.sndtimeo(100)
@socket.rcvtimeo(100)

# I do a ping each 30 sec
ping = => 
      version = @protocolVersion
      msgType = 20
      message = 0
      phone = 0
      message = [version,msgType,message,param].join ":"
      @socket.send message

setInterval ping, 30000

# Now I want to execute function when timeout occurs
@socket.on "I dont know what I can put here" , -> #my function

I tryed socket.on "error", "timeout", "survey-timeout", but didnt work.

**Comment by reqshark** [comment]
Oh I'm sorry I can't understand coffee, can u please translate into JS!

**Comment by GrimDev** [comment]
Yes.

This is the translation

// Init socket
var addr, ping, sock, socket;
socket = nano.socket("pair");
addr = "tcp://0.0.0.0:1665";
sock = this.socket.bind(addr);

// Params
this.socket.sndtimeo(100);
this.socket.rcvtimeo(100);

// Ping function
ping = (function(_this) {
  return function() {
    var message, msgType, phone, version;
    version = _this.protocolVersion;
    msgType = 20;
    message = 0;
    phone = 0;
    message = [version, msgType, message, param].join(":");
    return _this.socket.send(message);
  };
})(this);
setInterval(ping, 30000);

// Catch timeout
socket.on("timeout", function() { 
    console.log("Timeout catched !");
})

**Comment by reqshark** [comment]
Timeout has a special meaning in JS that doesn't apply here. 

maybe we should think about changing the language in the docs to "delay" to avoid that confusion in the future.

There's no timeout event that will fire here, it's just setting a silent delay on the socket I/O operation.

**Comment by GrimDev** [comment]
OK

I understood rcvtimeo and sndtimeo was the delay timeout, but I thought a timeout event is throw when it occurs.

I'll do a ping/pong to detect deconnections.

Thx for your replies.
