### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#77]
With PR: #65, were ready for a major version release.  We should add docs about the new pub sub channel support, and run `npm version major`.

**Comment by reqshark** [comment]
:+1: right on! 

I think we could either do the release now or wait for streams API changes, which could happen soon.

there are a couple implementation details to sort out with streams, but I think we're in good shape. 

so if we bump major now, we'll be looking at a v2 release in the near future as well

**Comment by nickdesaulniers** [comment]
release early, release often

**Comment by nickdesaulniers** [comment]
:house: :fire: :church: :hospital: :snail: :house_with_garden: :fire: :house: 
Oh no it's snailzilla!

       :sunny:                :helicopter: 
:cloud:            :cloud:               :cloud: 
______ :snail:     :evergreen_tree: :church: :deciduous_tree: 
It's headed for the orphanage!!!! :fearful:

**Comment by reqshark** [comment]
#### look! a gondola is running 
:sunny:                :helicopter: 
:cloud:            :cloud:               :cloud: 
______ :snail:     :evergreen_tree: :church: :deciduous_tree: :mountain_cableway: :deciduous_tree: must have been hidden beyond the trees earlier!
It's headed for the orphanage!!!! :fearful:
