### ISSUE TITLE
bad test case

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-nanomsg#82]
The test send.js says this on Travis in Node 0.10:

/home/travis/build/nickdesaulniers/node-nanomsg/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Object hello has no method 'equals'
    at Socket.<anonymous> (/home/travis/build/nickdesaulniers/node-nanomsg/test/send.js:87:17)
    at Socket.emit (events.js:95:17)
    at Socket._receive (/home/travis/build/nickdesaulniers/node-nanomsg/lib/index.js:184:10)
    at Socket.<anonymous> (/home/travis/build/nickdesaulniers/node-nanomsg/lib/index.js:198:30)

I'm pretty sure that's from this: https://github.com/nickdesaulniers/node-nanomsg/blob/master/test/send.js#L87 when I removed should.

**Comment by nickdesaulniers** [comment]
we should use [Buffer.compare](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_compare_buf1_buf2) and check that the result is 0.

**Comment by reqshark** [comment]
oh ya definitely `Buffer.compare(buf1, buf2)` looks sweet, we should do that in perf tests too!

what about just doing `t.equal(that,'thing')` as the replacement for should?

**Comment by nickdesaulniers** [comment]
Actually, [buf.equals is listed in the docs](https://nodejs.org/api/buffer.html#buffer_buf_equals_otherbuffer).  Was it not in 0.10?

**Comment by nickdesaulniers** [comment]
[Master 0.12](https://github.com/joyent/node/blob/ae58fc407f916b2abb164453a5b09273c543dbc3/lib/buffer.js#L296-L301).
0.10 does not exist!
