### ISSUE TITLE
unique prototypes for unique socket types

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#87]
this one cropped up during streams development in #53

just an idea that might help binding duplex stream `pull` sockets with built-in back-pressure.

I wonder if we can grab most of the general `Socket` class, like all the sockopt functions, and other properties and bring them over to a few type specific prototypes. 

In order to keep prototype inheritance boilerplate a bit cleaner, I copied the io.js `util.inherits()` core module function and made it cooler than school: https://github.com/reqshark/utildot

What if we had a generalized Socket with all the shared prototype methods and just pulled from a few child constructors with type-specific support?

**Comment by reqshark** [comment]
nevermind i dont know what i was thinking here

**Comment by nickdesaulniers** [comment]
don't bash yourself.  All ideas are welcome! :birthday: :100:
