### ISSUE TITLE
Question: Any way to guarantee pub.send delivery?

### ISSUE THREAD

**Issue by bmoelk** [nickdesaulniers/node-nanomsg#88]
I'd like to publish a message with a command line app and exit once I'm sure the message has been sent.

Although it appears pub.send is synchronous, it seems there are times when messages are lost due to latency issues. I've tried to increase the the linger value, but the only thing that seems to reliably send is if I sleep for a second before exiting.

It seems to me that although pub.send appear synchronous, it's really asynchronous. Is that the case?

**Comment by nickdesaulniers** [comment]
So if you set linger to 1000ms, node.js will exit before the message is sent?  I'm not sure how setTimeout and family signal to node.js not to shutdown, but we can probably add that signaling mechanism.  I'm curious if node's tcp stuff will wait to send then exit.  We reuse the default uv loop when sending and receiving messages, signaling when we should read from a file descriptor.  https://github.com/nickdesaulniers/node-nanomsg/blob/f08bdd09aee5ebafe1afbc98f231c70866fdcc04/src/node_nanomsg.cc#L258-L260

**Comment by nickdesaulniers** [comment]
Also, if you have a test case that shows the undesired behavior, that would be helpful.

**Comment by reqshark** [comment]
@bmoelk PUB messages are not guaranteed. You might try PUSH PULL.

**Comment by nickdesaulniers** [comment]
@reqshark can you cite that from the nanomsg man pages?  I was not able to find a reference.

**Comment by reqshark** [comment]
ya totally, the docs are weak in a lot of places.

hmm, it might be in an issue or mailing list. i'll see if i can find it

**Comment by bmoelk** [comment]
Thanks for the info re: pub/sub, I'll use push/pull for my purposes. FWIW, here is a gist to reproduce the behavior: https://gist.github.com/bmoelk/7b4e90eee1c820345b1f
