### ISSUE TITLE
Questions: is socket.send async? How do I intercept failed messages?

### ISSUE THREAD

**Issue by thelinuxlich** [nickdesaulniers/node-nanomsg#92]
I'm testing REQREP for a use case to replace Redis processing queue(using LPUSH and BRPOP) but I would like to store messages that no consumer got on redis for processing later.

**Comment by reqshark** [comment]
the Pipeline pattern works that way internally, namely: when no consumer receives the message, the pipeline's internal storage mechanism will distribute messages for processing later as a consumer becomes available. This is the `PUSH`/`PULL` combo.

Of course this is not the answer to your question: how to intercept failed messages.

and for reference, here's a list of the supported patterns:
* <strong>PAIR</strong> - simple one-to-one communication
* <strong>BUS</strong> - simple many-to-many communication
* <strong>REQREP</strong> - allows to build clusters of stateless services to process user requests
* <strong>PUBSUB</strong> - distributes messages to large sets of interested subscribers
* <strong>PIPELINE</strong>, a.k.a PUSHPULL</strong> - aggregates messages from multiple sources and load balances them among many destinations
* <strong>SURVEY</strong> - allows to query state of multiple applications in a single go

**Comment by thelinuxlich** [comment]
It's not exactly failed messages, but pending, see #93

**Comment by reqshark** [comment]
ok i'll take a look
