### ISSUE TITLE
REQ not sending ETIMEDOUT

### ISSUE THREAD

**Issue by thelinuxlich** [nickdesaulniers/node-nanomsg#93]
According to @gdamore on nanomsg gitter channel:

```
REQ will return ETIMEDOUT on recv() if the timeout expires.
```

So far I've tried every configuration possible and req.on("timeout", function() { ... }) never fires.

**Comment by gdamore** [comment]
Make sure the NN_RCVTIMEO option is set though!

**Comment by thelinuxlich** [comment]
Oh yeah, I've tried setting it to 1, nothing happened

**Comment by nickdesaulniers** [comment]
@thelinuxlich do you have a small test case we could add to our test suite to work against?

**Comment by gdamore** [comment]
Btw, ETIMEOUT does not apply to RAW sockets -- only to cooked ones.

**Comment by gdamore** [comment]
Huh.  In my testing I'm getting EAGAIN instead of ETIMEDOUT.  That's ... not what it should be.

**Comment by nickdesaulniers** [comment]
@gdamore , note we statically link an older version of Nanomsg.  If that was recently fixed, we can update our dependency.

**Comment by gdamore** [comment]
Huh.  In libnanomsg ETIMEDOUT is intentionally turned into EAGAIN: 
        rc = nn_efd_wait (&self->rcvfd, timeout);
        if (nn_slow (rc == -ETIMEDOUT))
            return -EAGAIN;

This feels like a mistake to me, but I need to make further research.  Nonetheless, EAGAIN or ETIMEDOUT -- you do get a timeout.  Blocking mode only of course.  (nonblocking sockets cannot distinguish a "timeout" as such.)

**Comment by thelinuxlich** [comment]
hmmm req.send is non-blocking in node-nanomsg? If it is we are lost concerning timeouts? :(

**Comment by thelinuxlich** [comment]
@nickdesaulniers  I'm trying to get the timeout event with this simple server implementation: https://gist.github.com/thelinuxlich/1e55ef121874d127ceca

**Comment by nickdesaulniers** [comment]
Well, you're missing a rep socket.  Req/rep are meant to be used as a pair.  I should add an example for this...

**Comment by nickdesaulniers** [comment]
for now, see [this test](https://github.com/nickdesaulniers/node-nanomsg/blob/c229c9ff5e0775264de1c0959efc4ea13662e979/test/ipc.js#L60-L84)

**Comment by thelinuxlich** [comment]
no, I'm testing exactly the absence of a consumer listening to see a timeout event

**Comment by nickdesaulniers** [comment]
indeed, we do not emit a timeout event anywhere.  Note the ability to specify socket options were added recently, and aren't fully tested other than check for their existence.  See #52.  What function in nanomsg returns ETIMEOUT or EAGAIN?  That would help me figure out how to wire it up.

**Comment by nickdesaulniers** [comment]
Stack looks like [nn_send](https://github.com/nanomsg/nanomsg/blob/a6dcc0ce7cf489e957e6f07ca756ac66f2420b36/src/core/global.c#L708) -> [nn_sendmsg](https://github.com/nanomsg/nanomsg/blob/a6dcc0ce7cf489e957e6f07ca756ac66f2420b36/src/core/global.c#L829) -> [nn_sock_send](https://github.com/nanomsg/nanomsg/blob/a6dcc0ce7cf489e957e6f07ca756ac66f2420b36/src/core/sock.c#L594-L595) -> EAGAIN

**Comment by thelinuxlich** [comment]
@gdamore said REQ is sending EAGAIN

**Comment by gdamore** [comment]
nn_recv gets the EAGAIN.
