### ISSUE TITLE
Something weird happens in REQREP when the server resends messages

### ISSUE THREAD

**Issue by thelinuxlich** [nickdesaulniers/node-nanomsg#95]
Server: https://gist.github.com/thelinuxlich/36290060a4bcda2aed79
Client: https://gist.github.com/thelinuxlich/a2397a5fd0768603e8e7

If I let the server run alone, it will try to send 10 messages with random strings. Then if I start a client, I can see after some seconds at least 7 messages going to it, BUT all of them with the last string sent.

**Comment by thelinuxlich** [comment]
Pinging @gdamore here to see if this is a expected nanomsg behavior

**Comment by thelinuxlich** [comment]
Actually it is not weird, it is really bad: I've left the client up for some time and it has received 18 messages!

**Comment by reqshark** [comment]
what happens if you don't set those socket options on the server?
