### ISSUE TITLE
Bad file descriptor [9] (../deps/nanomsg/src/aio/poller_epoll.inc:107)

### ISSUE THREAD

**Issue by 1N50MN14** [nickdesaulniers/node-nanomsg#98]
For some odd nanomsg crashes when used within a Docker container throwing an error `Bad file descriptor [9] (../deps/nanomsg/src/aio/poller_epoll.inc:107)`. TCP ports are exposed correctly. 

Any ideas as to why this might be happening? To see the crash, take any of the examples, dockerize and run.

**Comment by nickdesaulniers** [comment]
What's the file description that you passed to bind/connect?  That line number is in our fork [here](https://github.com/nickdesaulniers/nanomsg/blob/nn_rcvprio/src/aio/poller_epoll.inc#L107).  That `errno_assert` is probably a macro that prints `strerror(errno)`.  That function [doesn't look any different upstream](https://github.com/nanomsg/nanomsg/blob/master/src/aio/poller_epoll.inc#L107), so updating our fork probably wont help.

**Comment by 1N50MN14** [comment]
This is basically a snippet of my code:

```javascript
// Runs within the first Docker container, runs fine
var sock = nano.socket('pair')
sock.bind(protocol+'://‘+DOCKER_HOST+':’+DOCKER_PORT);
sock.on('message', function(buff){
   console.log(buff)
});
```

```javascript
// Runs within the second Docker container, this is where it crashes
var sock = nano.socket('pair');
sock.linger(0);
sock.connect(’tcp://'+SERVICE_HOST,’:’+SERVICE_PORT);
sock.on('message', function(buff){
  //console.log(buff)
});
```

**Comment by nickdesaulniers** [comment]
What if you perform the string concatenation first, store the resulting string in a temp variable and log it.  Can you start the DOCKER_HOST first, then see if you can connect to it via tellnet from or node's net library without nanomsg?

**Comment by nickdesaulniers** [comment]
`sock.connect('tcp://'+SERVICE_HOST,':'+SERVICE_PORT);` did you mean to have a comma in there? ;)

**Comment by 1N50MN14** [comment]
apologies this is just a typo  please ignore it, I find it faster to type than copy & paste on my new stupid Macbook ;)

**Comment by reqshark** [comment]
wait so is there a bad descriptor?

**Comment by 1N50MN14** [comment]
The line should read:
`sock.connect('tcp://'+SERVICE_HOST+':'+SERVICE_PORT);`

This is correct I even hardcoded the uri and manually tested it, it's not it.. exactly the same code running outside Docker (I'm basically mounting the volume where the code resides into the Docker container during development) works like a charm...

**Comment by nickdesaulniers** [comment]
on the second image, the client, try `require('net').connect(SERVICE_PORT, SERVICE_HOST)` and tell me if you see the same error.

**Comment by 1N50MN14** [comment]
@nickdesaulniers Yes I have started the Docker host first and checked the TCP port, also tried a simple socket connection (net.connect) which worked too

**Comment by nickdesaulniers** [comment]
Probably the next thing to check is to implement the same thing in C and see if it's an issue upstream.

**Comment by 1N50MN14** [comment]
@nickdesaulniers I just managed to get a basic code working (I still have to do some more tests), basically on the "server" side I was binding the socket to DOCKER IP (instead of 127.0.0.1 when running outside docker). 

To test the binding I logged `sock.bound['tcp://dockerhost:dockerport']` which returned 1, so I assumed all good here.

Now `net.createServer.listen()` takes a port argument, so I figured instead of relying docker ip to bind nanomsg I could try the network ipv6 address; I did just that and it worked! No bad filer descriptor error.

I need to do some more testing and double check that this is the case, what is strange though is that neither bind() nor connect() were throwing any errors.

Will update this thread with more details and confirm my findings once I've performed some more tests.

**Comment by 1N50MN14** [comment]
Obviously I'm still using docker ip with connect()

**Comment by 1N50MN14** [comment]
@nickdesaulniers @reqshark  Ok I can confirmed this is resolved and working like a charm ;) Thank you very much for the follow up (and for bringing nanomsg to node!!). Closing this issue.

**Comment by nickdesaulniers** [comment]
glad we could help, thanks for filing an issue to help us keep track

**Comment by reqshark** [comment]
:+1: 

btw when forming your connection address, you might try a named interface, like `eth0` or `lo0`: 

```js
socket.connect('tcp://eth0:64999');
```

and to find those, if you don't want to run `ifconfig`, just use `require('os').networkInterfaces()` for an object in node with a nice mapping of your machine's named interfaces

**Comment by 1N50MN14** [comment]
cool didn't know I could do that, right now I basically loop through the networkInterfaces() and retrieve the address which matches `!interface.internal && interface.family === 'IPv6'`. Will give the named interface approach a go!

**Comment by reqshark** [comment]
Oh `IPv6` in nanomsg is disabled by default. you might need to [set that option](https://github.com/nickdesaulniers/node-nanomsg#socketipv6boolean) before connect/bind:

```js
socket.ipv6(true);
```

**Comment by 1N50MN14** [comment]
@reqshark Strange this worked for me out of the box without calling `ipv6(true)`. The Docker container which I'm binding the ipv6 address has port forwarding I'm basically running it like so `docker run -p 5000:5000 myservice`. 

`connect` on the other hand within the other container relies on Docker IP which I believe is ipv4. Basically the flow is `connect(ipv4)` -> `ipv4` <-- port mapping --> `ipv6`. I'm not a networking expert but this is the flow which worked for me. This weekend / early next week I'm going to deploy the docker images on two separate AWS machines within a VPN and see if there are any surprises.

Still doesn't explain why binding socket to an ipv6 address worked without calling `ipv6(true)`, gonna look more into it see what I can find.
